services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    restart: unless-stopped
    user: "0:0"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Developer"
      MSSQL_COLLATION: "Japanese_CI_AS"
      MSSQL_MEMORY_LIMIT_MB: "8192"
      TZ: "Asia/Tokyo"
    volumes:
      - sqldata:/var/opt/mssql/data
      - sqllog:/var/opt/mssql/log
      - sqlbackup:/var/opt/mssql/backup
    deploy:
      resources:
        limits:
          memory: 10g
        reservations:
          memory: 4g

volumes:
  sqldata:
    driver: local
  sqllog:
    driver: local
  sqlbackup:
    driver: local
